//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linq_joins_ex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public long empid { get; set; }
        public string empname { get; set; }
        public string address { get; set; }
        public string emailid { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<long> deptid { get; set; }
    }
}
